spring.application.name=springweb

# 설정 : .properties 파일의 역할 설명
# application.properties 역할 : spring 관련 설정 값을 정의하는 곳
# 1. 서버 관련 설정 , 포트 지정 , 기본값 8080
server.port=8080

# 2. 데이터베이스 연결 설정
# 2-1 연결할 DB 주소
spring.datasource.url=jdbc:mysql://localhost:3306/mydb0902
# 2-2 DB접속 아이디/비밀번호
spring.datasource.username=root
spring.datasource.password=1234

