spring.application.name=springweb

# ?? : .properties ??? ?? ??
# aplication.properties ?? : spring ?? ?? ?? ???? ?
# 1. ?? ??? ?? ?? ?? , ??? 8080
server.port=8080

# 2. ?????? ??
# 2-1 ??? DB ??
spring.datasource.url=jdbc:mysql://localhost:3306/mydb0902
# 2-2 DB??? ???/????
spring.datasource.username=root
spring.datasource.password=1234

